apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: is-nodejs-runtime
spec:
  params:
    - name: OW_APP_PATH
      type: string
  resources:
    - name: app-git
      type: git
  check:
    image: ubuntu
    command:
      - bash
    args:
      - -c
      - |
        find $(params.OW_APP_PATH) -type f | sed -e 's/.*\.//' | sed -e 's/.*\///' | sort -u | grep ^js$
---


apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: is-java-runtime
spec:
  params:
    - name: OW_APP_PATH
      type: string
  resources:
    - name: app-git
      type: git
  check:
    image: ubuntu
    command:
      - bash
    args:
      - -c
      - |
        find $(params.OW_APP_PATH) -type f | sed -e 's/.*\.//' | sed -e 's/.*\///' | sort -u | grep ^java$
---

apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-build-archive
spec:
  inputs:
    resources:
      - name: app-git
        type: git
    params:
      - name: OW_APP_PATH
        default: ""
  outputs:
    resources:
      - name: app-git
        type: git
  steps:
    - name: build-action-archive
      image: node
      script: |
        #!/usr/bin/env bash
        apt-get update && apt-get install zip
        cd $(inputs.params.OW_APP_PATH) && zip action.zip -r *

