# Git Pipeline Resource for an application GitHub Repo
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
    name: app-git
spec:
    type: git
    params:
        - name: revision
          value: master
        - name: url
          value: https://github.com/apache/openwhisk-test.git
---

# Task to clone GitHub repo and display a file contents
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
    name: task-clone-source
spec:
    inputs:
        resources:
            - name: git-repo
              type: git
        params:
            - name: NODE_VERSION
              default: "node"
            - name: APP_DIR
              default: ""
            - name: ARCHIVE_UTILITY
              default: "zip"
            - name: ACTION_ARCHIVE_NAME
              default: "action.zip"
    steps:
        - name: install-node 
          image: $(inputs.params.NODE_VERSION)
          command:
            - bash
          args:
            - -c
            - |
              npm install --prefix $(inputs.params.APP_DIR)
              apt-get update && apt-get install $(inputs.params.ARCHIVE_UTILITY) 
              cd $(inputs.params.APP_DIR) && $(inputs.params.ARCHIVE_UTILITY) $(inputs.params.ACTION_ARCHIVE_NAME) -r *
              base64 $(inputs.params.ACTION_ARCHIVE_NAME) | tr -d '[:space:]'
---

# Pipeline

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
    name: build-openwhisk-app
spec:
    params:
        - name: APP_DIR
          type: string
    resources:
        - name: app-git-repo
          type: git
    tasks:
        - name: build-app
          taskRef:
            name: task-clone-source
          resources:
            inputs:
                - name: git-repo
                  resource: app-git-repo
          params:
              - name: APP_DIR
                value: $(params.APP_DIR)

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
    name: run-build-openwhisk-app
spec:
    pipelineRef:
        name: build-openwhisk-app
    resources:
        - name: app-git-repo
          resourceRef:
            name: app-git 
    params:
        - name: APP_DIR
          value: "/workspace/git-repo/packages/left-pad/"
    
---

## Task Run to Clone a GitHub repo and install npm
#apiVersion: tekton.dev/v1alpha1
#kind: TaskRun
#metadata:
#    name: taskrun-clone-source
#spec:
#    inputs:
#        resources:
#            - name: git-repo
#              resourceRef:
#                name: app-git
#        params:
#            - name: APP_DIR
#              value: "/workspace/git-repo/packages/left-pad/"
#    taskRef:
#        name: task-clone-source
#
#---
