apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: openwhisk-java-app
spec:
  params:
    - name: OW_APP_PATH
      description: "Relative or Absolute path of the application source in the GitHub repo"
      type: string
      default: ""
    - name: OW_APP_JAVA_VERSION
      description: "Any specific Node version needed to compile/run application source on"
      type: string
      default: "adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u222-b10_openj9-0.15.1"
  resources:
    - name: app-git
      type: git
  tasks:
    #####################################################################
    # Task to Clone Application Source and Run Build Gradle
    - name: run-build-gradle
      taskRef:
        name: task-build-gradle
      resources:
        inputs:
          - name: app-git
            resource: app-git
        outputs:
          - name: app-git
            resource: app-git
      params:
        - name: OW_APP_PATH
          value: $(params.OW_APP_PATH)
        - name: OW_APP_JAVA_VERSION
          value: $(params.OW_APP_JAVA_VERSION)