apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-openwhisk-app
spec:
  params:
    - name: OW_APP_PATH
      type: string
    - name: OW_APP_NODE_VERSION
      type: string
    - name: OW_ACTION_ARCHIVE_NAME
      type: string
    - name: DOCKERFILE
    - name: OW_RUNTIME_DEBUG
      type: string
    - name: OW_RUNTIME_PLATFORM
      type: string
    - name: OW_ACTION_NAME
      type: string
    - name: OW_ACTION_CODE
      type: string
    - name: OW_ACTION_MAIN
      type: string
    - name: OW_ACTION_BINARY
      type: string
    - name: OW_HTTP_METHODS
      type: string
    - name: OW_ACTION_RAW
      type: string
  resources:
    - name: app-git
      type: git
    - name: runtime-git
      type: git
    - name: app-image
      type: image
  tasks:
    #####################################################################
    # Task to Clone Application Source and Install necessary Dependencies
    - name: install-npm-packages
      taskRef:
        name: task-install-npm-packages
      conditions:
        - conditionRef: is-nodejs-runtime
          params:
            - name: OW_APP_PATH
              value: $(params.OW_APP_PATH)
      resources:
        inputs:
          - name: app-git
            resource: app-git
        outputs:
          - name: app-git
            resource: app-git
      params:
        - name: OW_APP_PATH
          value: $(params.OW_APP_PATH)
        - name: OW_APP_NODE_VERSION
          value: $(params.OW_APP_NODE_VERSION)
    #####################################################################
    # Task to archive application source
    - name: build-archive
      taskRef:
        name: task-build-archive
      conditions:
        - conditionRef: is-nodejs-runtime
          params:
            - name: OW_APP_PATH
              value: $(params.OW_APP_PATH)
      resources:
        inputs:
          - name: app-git
            resource: app-git
        outputs:
          - name: app-git
            resource: app-git
      params:
        - name: OW_APP_PATH
          value: $(params.OW_APP_PATH)
        - name: OW_APP_NODE_VERSION
          value: $(params.OW_APP_NODE_VERSION)
        - name: OW_ACTION_ARCHIVE_NAME
          value: $(params.OW_ACTION_ARCHIVE_NAME)
    #####################################################################
    # Task to build an image with OpenWhisk Runtime and Application Source
    - name: build-openwhisk-app-image
      taskRef:
        name: openwhisk
      resources:
        inputs:
          - name: app-git
            resource: app-git
          - name: runtime-git
            resource: runtime-git
        outputs:
          - name: app-image
            resource: app-image
      params:
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: OW_RUNTIME_DEBUG
          value: $(params.OW_RUNTIME_DEBUG)
        - name: OW_RUNTIME_PLATFORM
          value: $(params.OW_RUNTIME_PLATFORM)
        - name: OW_ACTION_NAME
          value: $(params.OW_ACTION_NAME)
        - name: OW_ACTION_CODE
          value: $(params.OW_ACTION_CODE)
        - name: OW_ACTION_MAIN
          value: $(params.OW_ACTION_MAIN)
        - name: OW_ACTION_BINARY
          value: $(params.OW_ACTION_BINARY)
        - name: OW_HTTP_METHODS
          value: $(params.OW_HTTP_METHODS)
        - name: OW_ACTION_RAW
          value: $(params.OW_ACTION_RAW)
    #####################################################################
