apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: openwhisk-java-app
spec:
  params:
    - name: OW_APP_PATH
      description: "Relative or Absolute path of the application source in the GitHub repo"
      type: string
      default: ""
    - name: OW_APP_JAVA_VERSION
      description: "Any specific Node version needed to compile/run application source on"
      type: string
      default: "adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u222-b10_openj9-0.15.1"
    - name: DOCKERFILE
      description: "The path to the dockerfile to build from Runtime Repo"
      type: string
      default: "Dockerfile"
    - name: OW_RUNTIME_CONTEXT
      description: "The path to the dockerfile to build from Runtime Repo"
      type: string
      default: "dir:///workspace"
    - name: OW_BUILD_CONFIG_PATH
      description: "The path to the build configuration script (build.gradle) in Runtime Repo"
      default: "core/java8/proxy/"
    - name: OW_RUNTIME_DEBUG
      description: "flag to indicate debug mode should be on/off"
      type: string
      default: "false"
    - name: OW_RUNTIME_PLATFORM
      description: "flag to indicate the platform, one of [openwhisk, knative, ... ]"
      type: string
      default: "knative"
    - name: OW_ACTION_NAME
      description: "name of the action"
      type: string
      default: ""
    - name: OW_ACTION_CODE
      description: "JavaScript source code to be evaluated"
      type: string
      default: ""
    - name: OW_ACTION_MAIN
      description: "name of the function in the __OW_ACTION_CODE to call as the action handler"
      type: string
      default: "main"
    - name: OW_ACTION_BINARY
      description: "flag to indicate zip function, for zip actions, __OW_ACTION_CODE must be base64 encoded string"
      type: string
      default: "true"
    - name: OW_HTTP_METHODS
      description: "list of HTTP methods, any combination of [GET, POST, PUT, and DELETE], default is [POST]"
      type: string
      default: "[POST]"
    - name: OW_ACTION_RAW
      description: "flag to indicate raw HTTP handling, interpret and process an incoming HTTP body directly"
      type: string
      default: "false"
  resources:
    - name: app-git
      type: git
    - name: runtime-git
      type: git
    - name: app-image
      type: image
  tasks:
    #####################################################################
    # Task to Clone Application Source and Run Build Gradle
    - name: run-build-gradle
      taskRef:
        name: embed-java-profile
      resources:
        inputs:
          - name: runtime-git
            resource: runtime-git
        outputs:
          - name: runtime-git
            resource: runtime-git
      params:
        - name: OW_APP_JAVA_VERSION
          value: $(params.OW_APP_JAVA_VERSION)
        - name: OW_BUILD_CONFIG_PATH
          value: $(params.OW_BUILD_CONFIG_PATH)
    #####################################################################
    # Task to Clone Application Source and Run Build Gradle
    - name: create-one-jar
      taskRef:
        name: create-one-jar
      resources:
        inputs:
          - name: runtime-git
            resource: runtime-git
            from:
              - run-build-gradle
        outputs:
          - name: runtime-git
            resource: runtime-git
      params:
        - name: OW_APP_JAVA_VERSION
          value: $(params.OW_APP_JAVA_VERSION)
        - name: OW_BUILD_CONFIG_PATH
          value: $(params.OW_BUILD_CONFIG_PATH)
    #####################################################################
    - name: openwhisk-java-runtime
      taskRef:
        name: openwhisk-java-runtime
      resources:
        inputs:
          - name: app-git
            resource: app-git
          - name: runtime-git
            resource: runtime-git
            from:
              - create-one-jar
        outputs:
          - name: app-image
            resource: app-image
      params:
        - name: OW_APP_PATH
          value: $(params.OW_APP_PATH)
#        - name: OW_APP_JAVA_VERSION
#          value: $(params.OW_APP_JAVA_VERSION)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: OW_RUNTIME_CONTEXT
          value: $(params.OW_RUNTIME_CONTEXT)
        - name: OW_RUNTIME_DEBUG
          value: $(params.OW_RUNTIME_DEBUG)
        - name: OW_RUNTIME_PLATFORM
          value: $(params.OW_RUNTIME_PLATFORM)
        - name: OW_ACTION_NAME
          value: $(params.OW_ACTION_NAME)
        - name: OW_ACTION_CODE
          value: $(params.OW_ACTION_CODE)
        - name: OW_ACTION_MAIN
          value: $(params.OW_ACTION_MAIN)
        - name: OW_ACTION_BINARY
          value: $(params.OW_ACTION_BINARY)
        - name: OW_HTTP_METHODS
          value: $(params.OW_HTTP_METHODS)
        - name: OW_ACTION_RAW
          value: $(params.OW_ACTION_RAW)
        - name: OW_APP_PATH
          value: $(params.OW_APP_PATH)
