# Task to clone application source
#
# Inputs:
#   * app-git: GitHub Repo with application source
#
# Outputs:
#   * app-git: GitHub Repo with application source
#
#
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-clone-source
spec:
  inputs:
    resources:
      - name: app-git
        type: git
  outputs:
    resources:
      - name: app-git
        type: git
  steps:
    - name: list-app-source
      image: ubuntu
      command:
        - bash
      args:
        - -c
        - |
          ls $(inputs.resources.app-git.path)