apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-openwhisk-app
spec:
  workspaces:
    - name: openwhisk-workspace
  params:
    - name: OW_APP_PATH
      description: "Relative or Absolute path of the application source in the GitHub repo"
      type: string
      default: ""
    - name: OW_APP_NODE_VERSION
      description: "Any specific Node version needed to compile/run application source on"
      type: string
      default: "node"
    - name: OW_ACTION_ARCHIVE_NAME
      type: string
      default: "action.zip"
    - name: DOCKERFILE
      description: "The path to the dockerfile to build from Runtime Repo"
      type: string
      default: "Dockerfile"
    - name: OW_RUNTIME_DEBUG
      description: "flag to indicate debug mode should be on/off"
      type: string
      default: "false"
    - name: OW_RUNTIME_PLATFORM
      description: "flag to indicate the platform, one of [openwhisk, knative, ... ]"
      type: string
      default: "knative"
    - name: OW_ACTION_NAME
      description: "name of the action"
      type: string
      default: ""
    - name: OW_ACTION_CODE
      description: "JavaScript source code to be evaluated"
      type: string
      default: ""
    - name: OW_ACTION_MAIN
      description: "name of the function in the __OW_ACTION_CODE to call as the action handler"
      type: string
      default: "main"
    - name: OW_ACTION_BINARY
      description: "flag to indicate zip function, for zip actions, __OW_ACTION_CODE must be base64 encoded string"
      type: string
      default: "true"
    - name: OW_HTTP_METHODS
      description: "list of HTTP methods, any combination of [GET, POST, PUT, and DELETE], default is [POST]"
      type: string
      default: "[POST]"
    - name: OW_ACTION_RAW
      description: "flag to indicate raw HTTP handling, interpret and process an incoming HTTP body directly"
      type: string
      default: "false"
    # Parameters for Java Applications
    - name: OW_APP_JAVA_VERSION
      description: "Any specific Node version needed to compile/run application source on"
      type: string
      default: "adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u222-b10_openj9-0.15.1"
    - name: OW_RUNTIME_CONTEXT
      description: "The path to the dockerfile to build from Runtime Repo"
      type: string
      default: "dir:///workspace"
    - name: OW_BUILD_CONFIG_PATH
      description: "The path to the build configuration script (build.gradle) in Runtime Repo"
      default: "core/java8/proxy/"
    - name: JAR_NAME
      description: "Jar name of the application source"
      type: string
      default: "OWAutoInit"
    - name: MAVEN_BUILD_OUTPUT_PATH
      description: "Maven build path where the jar file is created"
      type: string
      default: "./"
    - name: OW_AUTO_INIT_MAIN
      description: "Function name"
      type: string
      default: "main"
  resources:
    - name: app-git
      type: git
    - name: runtime-git
      type: git
    - name: app-image
      type: image
  tasks:
    #####################################################################
    # Task to Clone Application Source and Install necessary Dependencies
    - name: install-npm-packages
      taskRef:
        name: task-install-npm-packages
      conditions:
        - conditionRef: is-nodejs-runtime
          params:
            - name: OW_APP_PATH
              value: $(params.OW_APP_PATH)
          resources:
            - name: app-git
              resource: app-git
      workspaces:
        - name: openwhisk-workspace
          workspace: openwhisk-workspace
      resources:
        inputs:
          - name: app-git
            resource: app-git
      params:
        - name: OW_APP_PATH
          value: $(params.OW_APP_PATH)
        - name: OW_APP_NODE_VERSION
          value: $(params.OW_APP_NODE_VERSION)
    #####################################################################
    # Task to archive application source
    - name: build-archive
      taskRef:
        name: task-build-archive
      runAfter:
        - install-npm-packages
      workspaces:
        - name: openwhisk-workspace
          workspace: openwhisk-workspace
      params:
        - name: OW_APP_PATH
          value: $(params.OW_APP_PATH)
        - name: OW_APP_NODE_VERSION
          value: $(params.OW_APP_NODE_VERSION)
        - name: OW_ACTION_ARCHIVE_NAME
          value: $(params.OW_ACTION_ARCHIVE_NAME)
    #####################################################################
    # Task to build an image with OpenWhisk Runtime and Application Source
    - name: build-openwhisk-app-image
      taskRef:
        name: openwhisk
      runAfter:
        - build-archive
      workspaces:
        - name: openwhisk-workspace
          workspace: openwhisk-workspace
      resources:
        inputs:
          - name: runtime-git
            resource: runtime-git
        outputs:
          - name: app-image
            resource: app-image
      params:
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: OW_RUNTIME_DEBUG
          value: $(params.OW_RUNTIME_DEBUG)
        - name: OW_RUNTIME_PLATFORM
          value: $(params.OW_RUNTIME_PLATFORM)
        - name: OW_ACTION_NAME
          value: $(params.OW_ACTION_NAME)
        - name: OW_ACTION_CODE
          value: $(params.OW_ACTION_CODE)
        - name: OW_ACTION_MAIN
          value: $(params.OW_ACTION_MAIN)
        - name: OW_ACTION_BINARY
          value: $(params.OW_ACTION_BINARY)
        - name: OW_HTTP_METHODS
          value: $(params.OW_HTTP_METHODS)
        - name: OW_ACTION_RAW
          value: $(params.OW_ACTION_RAW)
        - name: OW_APP_PATH
          value: $(params.OW_APP_PATH)
        - name: OW_ACTION_ARCHIVE_NAME
          value: $(params.OW_ACTION_ARCHIVE_NAME)
    #####################################################################
    # Create application JAR with maven
    - name: create-jar-with-maven
      taskRef:
        name: create-jar-with-maven
      conditions:
        - conditionRef: is-java-runtime
          params:
            - name: OW_APP_PATH
              value: $(params.OW_APP_PATH)
          resources:
            - name: app-git
              resource: app-git
      workspaces:
        - name: openwhisk-workspace
          workspace: openwhisk-workspace
      resources:
        inputs:
          - name: app-git
            resource: app-git
      params:
        - name: MAVEN_BUILD_OUTPUT_PATH
          value: $(params.MAVEN_BUILD_OUTPUT_PATH)
        - name: JAR_NAME
          value: $(params.JAR_NAME)
    #####################################################################
    # Build runtime with gradle, run after creating application JAR
    - name: build-runtime-with-gradle
      taskRef:
        name: build-runtime-with-gradle
      runAfter:
        - create-jar-with-maven
      workspaces:
        - name: openwhisk-workspace
          workspace: openwhisk-workspace
      resources:
        inputs:
          - name: runtime-git
            resource: runtime-git
      params:
        - name: OW_APP_JAVA_VERSION
          value: $(params.OW_APP_JAVA_VERSION)
        - name: OW_BUILD_CONFIG_PATH
          value: $(params.OW_BUILD_CONFIG_PATH)
    #####################################################################
    # Build shared class cache, run after building runtime
    - name: build-shared-class-cache
      taskRef:
        name: build-shared-class-cache
      runAfter:
        - build-runtime-with-gradle
      workspaces:
        - name: openwhisk-workspace
          workspace: openwhisk-workspace
      params:
        - name: OW_APP_JAVA_VERSION
          value: $(params.OW_APP_JAVA_VERSION)
        - name: OW_BUILD_CONFIG_PATH
          value: $(params.OW_BUILD_CONFIG_PATH)
    #####################################################################
    # Finalize runtime with function source - JAR file, run after building shared class cache
    - name: finalize-runtime-with-function
      taskRef:
        name: finalize-runtime-with-function
      runAfter:
        - build-shared-class-cache
      workspaces:
        - name: openwhisk-workspace
          workspace: openwhisk-workspace
      resources:
        outputs:
          - name: app-image
            resource: app-image
      params:
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: OW_RUNTIME_CONTEXT
          value: $(params.OW_RUNTIME_CONTEXT)
        - name: MAVEN_BUILD_OUTPUT_PATH
          value: $(params.MAVEN_BUILD_OUTPUT_PATH)
        - name: JAR_NAME
          value: $(params.JAR_NAME)
        - name: OW_AUTO_INIT_MAIN
          value: $(params.OW_AUTO_INIT_MAIN)
