# Git Pipeline Resource representing an application source on GitHub
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-git
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.com/apache/openwhisk-test.git
---

# Task to clone GitHub repo and display a file contents
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-clone-source
spec:
  inputs:
    resources:
    - name: git-repo
      type: git
    params:
    - name: APP_DIR
      default: ""
    - name: LANGUAGE
      default: "javascript"
  outputs:
    resources:
    - name: git-repo
      type: git
      targetPath: "javascript/" 
  steps:
  - name: detect-language 
    image: ubuntu 
    command:
    - bash
    args:
    - -c
    - |
      cd $(inputs.params.APP_DIR)
      ls -R /workspace
---

# Task Run to Clone a GitHub repo and install npm
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: taskrun-clone-source
spec:
  inputs:
    resources:
    - name: git-repo
      resourceRef:
        name: app-git
    params:
    - name: APP_DIR
      value: "/workspace/git-repo/packages/left-pad/"
  outputs:
    resources:
    - name: git-repo
      resourceRef:
        name: app-git
  taskRef:
    name: task-clone-source

---
