apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-runtime-with-gradle
spec:
  inputs:
    resources:
      - name: runtime-git
        type: git
    params:
      - name: OW_APP_JAVA_VERSION
        default: "adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u222-b10_openj9-0.15.1"
        description: "Any specific OpenJDK version needed to compile/run application source on"
      - name: OW_BUILD_CONFIG_PATH
        description: "The path to the build configuration script (build.gradle) in Runtime Repo"
        default: "core/java8/proxy/"
  outputs:
    resources:
      - name: runtime-git
        type: git
  steps:
    - name: build-runtime-with-gradle
      image: $(inputs.params.OW_APP_JAVA_VERSION)
      script: |
        #!/usr/bin/env bash
        set -xe
        cp -r $(inputs.resources.runtime-git.path)/* $(outputs.resources.runtime-git.path)
        cd $(outputs.resources.runtime-git.path)/$(inputs.params.OW_BUILD_CONFIG_PATH) && ./gradlew copyDependencies
