apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: openwhisk-java-runtime
spec:
  inputs:
    resources:
      - name: runtime-git
        type: git
    params:
      - name: DOCKERFILE
        description: "The path to the dockerfile to build from Runtime Repo"
        default: "Dockerfile"
      - name: OW_RUNTIME_CONTEXT
        description: "The path to the dockerfile to build from Runtime Repo"
        default: "dir:///workspace/runtime-git/"
  outputs:
    resources:
      - name: app-image
        type: image
  steps:
    - name: update-dockerfile-for-tekton
      image: ubuntu
      command:
        - bash
      args:
        - -c
        - |
          DOCKERFILE_PATH=`echo "$(inputs.params.OW_RUNTIME_CONTEXT)" | sed 's/^dir:\/\///'`
          sed -i -e 's/&& rm -rf .classpath .gitignore .gradle .project .settings Dockerfile build \\//g' $DOCKERFILE_PATH/$(inputs.params.DOCKERFILE)
          sed -i -e 's/&& \.\/gradlew oneJar \\//g' $DOCKERFILE_PATH/$(inputs.params.DOCKERFILE)
          sed -i -e 's/&& rm -rf \/javaAction\/src \\//g' $DOCKERFILE_PATH/$(inputs.params.DOCKERFILE)
          sed -i -e 's/&& \.\/gradlew copyDependencies \\//g' $DOCKERFILE_PATH/$(inputs.params.DOCKERFILE)
    - name: build-openwhisk-app-image
      image: "gcr.io/kaniko-project/executor:latest"
      command:
        - /kaniko/executor
      args:
        - --context=$(inputs.params.OW_RUNTIME_CONTEXT)
        - --dockerfile=$(inputs.params.DOCKERFILE)
        - --destination=$(outputs.resources.app-image.url)
