apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-maven-against-pom
spec:
  inputs:
    resources:
      - name: app-git
        type: git
  outputs:
    resources:
      - name: app-git
        type: git
  steps:
    - name: build-with-maven
      image: maven:latest
      command:
        - mvn
      args:
        - -f
        - $(inputs.resources.app-git.path)/
        - package
    - name: copy-input-to-output
      image: ubuntu
      command:
        - bash
      args:
        - -c
        - cp -r $(inputs.resources.app-git.path)/* $(outputs.resources.app-git.path)
