apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: run-maven-against-pom
spec:
  inputs:
    resources:
      - name: app-git
        type: git
  outputs:
    resources:
      - name: app-git
        type: git
  steps:
    - name: build-with-maven
      image: maven:latest
      command:
        - mvn
      args:
        - -f
        - $(inputs.resources.app-git.path)/
        - package
    - name: copy-input-to-output
      image: ubuntu
      command:
        - bash
      args:
        - -c
        - |
          cp -r $(inputs.resources.app-git.path)/* $(outputs.resources.app-git.path)
    - name: list-out-jar-content
      image: "adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u222-b10_openj9-0.15.1"
      command:
        - bash
      args:
        - -c
        - |
          jar tf /workspace/app-git/target/java-openwhisk-example-app-1.0-SNAPSHOT.jar
