apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-one-jar
spec:
  inputs:
    resources:
      - name: runtime-git
        type: git
    params:
      - name: OW_APP_JAVA_VERSION
        default: "adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u222-b10_openj9-0.15.1"
        description: "Any specific OpenJDK version needed to compile/run application source on"
      - name: OW_BUILD_CONFIG_PATH
        description: "The path to the build configuration script (build.gradle) in Runtime Repo"
        default: "core/java8/proxy/"
  outputs:
    resources:
      - name: runtime-git
        type: git
  steps:
    - name: create-one-jar
      image: $(inputs.params.OW_APP_JAVA_VERSION)
      command:
        - bash
      args:
        - -c
        - |
          echo "Copy Java runtime repo from $(inputs.resources.runtime-git.path) to $(outputs.resources.runtime-git.path)"
          echo "INFO: cp -r $(inputs.resources.runtime-git.path) $(outputs.resources.runtime-git.path)"
          cp -r $(inputs.resources.runtime-git.path)/* $(outputs.resources.runtime-git.path)
          if [ $? = 0 ]; then
            echo "INFO: Successfully copied Java runtime repo from $(inputs.resources.runtime-git.path) to $(outputs.resources.runtime-git.path)"
            cd $(outputs.resources.runtime-git.path)/$(inputs.params.OW_BUILD_CONFIG_PATH)
            echo "INFO: Creating oneJar under $(inputs.params.OW_BUILD_CONFIG_PATH)"
            ./gradlew oneJar
            if [ $? = 0 ]; then
              echo "INFO: Successfully created oneJar under $(inputs.params.OW_BUILD_CONFIG_PATH)"
              echo "INFO: Renaming JAR file to javaAction-all.jar"
              mv build/libs/proxy-all.jar build/libs/javaAction-all.jar
            else
              echo "Failed to create oneJar under $(inputs.params.OW_BUILD_CONFIG_PATH)"
            fi
          else
            echo "ERROR: Failed to copy Java runtime repo from $(inputs.resources.runtime-git.path) to $(outputs.resources.runtime-git.path)"
          fi
