# Task to Compile Java Application
#
# Inputs:
#   * app-git: GitHub repo with an Application Source
#   * OW_APP_NODE_VERSION: any specific Node Version you want to pull, default is "node"
#   * OW_APP_PATH: path to application directory within the GitHub repo, default is ""
#
# OutPuts:
#   * app-git: GitHub repo with an Application Source along with all the dependencies installed
#
# Application source is cloned under /workspace/<resource-name> by default if targetPath is not specified.
#
# This task installs third party packages under /workspace/<resource-name>/<app_path>/
#
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-build-gradle
spec:
  inputs:
    resources:
      - name: app-git
        type: git
    params:
      - name: OW_APP_JAVA_VERSION
        default: "adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u222-b10_openj9-0.15.1"
        description: "Any specific OpenJDK version needed to compile/run application source on"
      - name: OW_APP_PATH
        default: ""
        description: "Relative or Absolute path to the application source to the build.gradle"
  outputs:
    resources:
      - name: app-git
        type: git
  steps:
    - name: build-gradle
      image: $(inputs.params.OW_APP_JAVA_VERSION)
      command:
        - bash
      args:
        - -c
        - |
          echo "Running gradle from $(inputs.params.OW_APP_PATH)"
          cd $(inputs.params.OW_APP_PATH)
          ./gradlew copyDependencies
          if [ $? = 0 ]; then
            echo "Successfully finished running gradle $(inputs.params.OW_APP_PATH)"
          else
            echo "Failed to run gradle under $(inputs.params.OW_APP_PATH)"
          fi
