apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: openwhisk-java-app
spec:
  params:
    - name: OW_APP_JAVA_VERSION
      description: "Any specific Node version needed to compile/run application source on"
      type: string
      default: "adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u222-b10_openj9-0.15.1"
    - name: DOCKERFILE
      description: "The path to the dockerfile to build from Runtime Repo"
      type: string
      default: "Dockerfile"
    - name: OW_RUNTIME_CONTEXT
      description: "The path to the dockerfile to build from Runtime Repo"
      type: string
      default: "dir:///workspace"
    - name: OW_BUILD_CONFIG_PATH
      description: "The path to the build configuration script (build.gradle) in Runtime Repo"
      default: "core/java8/proxy/"
  resources:
    - name: app-git
      type: git
    - name: runtime-git
      type: git
    - name: app-image
      type: image
  tasks:
    #####################################################################
    # Task to Clone App Source and build app jar with maven
    - name: create-jar-file-with-maven
      taskRef:
        name: run-maven-against-pom
      resources:
        inputs:
          - name: app-git
            resource: app-git
        outputs:
          - name: app-git
            resource: app-git
    #####################################################################
    # Task to Clone Application Source and Run Build Gradle
    - name: run-build-gradle
      taskRef:
        name: embed-java-profile
      resources:
        inputs:
          - name: app-git
            resource: app-git
            from:
              - create-jar-file-with-maven
          - name: runtime-git
            resource: runtime-git
        outputs:
          - name: runtime-git
            resource: runtime-git
      params:
        - name: OW_APP_JAVA_VERSION
          value: $(params.OW_APP_JAVA_VERSION)
        - name: OW_BUILD_CONFIG_PATH
          value: $(params.OW_BUILD_CONFIG_PATH)
    #####################################################################
    # Task to Clone Application Source and Run Build Gradle
    - name: create-one-jar
      taskRef:
        name: create-one-jar
      resources:
        inputs:
          - name: runtime-git
            resource: runtime-git
            from:
              - run-build-gradle
        outputs:
          - name: runtime-git
            resource: runtime-git
      params:
        - name: OW_APP_JAVA_VERSION
          value: $(params.OW_APP_JAVA_VERSION)
        - name: OW_BUILD_CONFIG_PATH
          value: $(params.OW_BUILD_CONFIG_PATH)
    #####################################################################
    - name: openwhisk-java-runtime
      taskRef:
        name: openwhisk-java-runtime
      resources:
        inputs:
          - name: runtime-git
            resource: runtime-git
            from:
              - create-one-jar
        outputs:
          - name: app-image
            resource: app-image
      params:
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: OW_RUNTIME_CONTEXT
          value: $(params.OW_RUNTIME_CONTEXT)
