apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: openwhisk-java-app
spec:
  params:
    - name: OW_APP_JAVA_VERSION
      description: "Any specific Node version needed to compile/run application source on"
      type: string
      default: "adoptopenjdk/openjdk8-openj9:x86_64-ubuntu-jdk8u222-b10_openj9-0.15.1"
    - name: DOCKERFILE
      description: "The path to the dockerfile to build from Runtime Repo"
      type: string
      default: "Dockerfile"
    - name: OW_RUNTIME_CONTEXT
      description: "The path to the dockerfile to build from Runtime Repo"
      type: string
      default: "dir:///workspace"
    - name: OW_BUILD_CONFIG_PATH
      description: "The path to the build configuration script (build.gradle) in Runtime Repo"
      default: "core/java8/proxy/"
    - name: JAR_NAME
      description: "Jar name of the application source"
      type: string
      default: "OWAutoInit"
    - name: MAVEN_BUILD_OUTPUT_PATH
      description: "Maven build path where the jar file is created"
      type: string
      default: "./"
    - name: OW_AUTO_INIT_MAIN
      description: "Function name"
      type: string
      default: "main"
  resources:
    - name: app-git
      type: git
    - name: runtime-git
      type: git
    - name: app-image
      type: image
  tasks:
    #####################################################################
    # Task to Clone App Source and build app jar with maven
    - name: create-jar-with-maven
      taskRef:
        name: create-jar-with-maven
      resources:
        inputs:
          - name: app-git
            resource: app-git
        outputs:
          - name: app-git
            resource: app-git
      params:
        - name: MAVEN_BUILD_OUTPUT_PATH
          value: $(params.MAVEN_BUILD_OUTPUT_PATH)
        - name: JAR_NAME
          value: $(params.JAR_NAME)
    #####################################################################
    # Task to Clone Application Source and Run Build Gradle
    - name: build-shared-class-cache
      taskRef:
        name: build-shared-class-cache
      resources:
        inputs:
          - name: runtime-git
            resource: runtime-git
        outputs:
          - name: runtime-git
            resource: runtime-git
      params:
        - name: OW_APP_JAVA_VERSION
          value: $(params.OW_APP_JAVA_VERSION)
        - name: OW_BUILD_CONFIG_PATH
          value: $(params.OW_BUILD_CONFIG_PATH)
    #####################################################################
    # Task to Clone Application Source and Run Build Gradle
    - name: build-runtime-with-gradle
      taskRef:
        name: build-runtime-with-gradle
      resources:
        inputs:
          - name: runtime-git
            resource: runtime-git
            from:
              - build-shared-class-cache
        outputs:
          - name: runtime-git
            resource: runtime-git
      params:
        - name: OW_APP_JAVA_VERSION
          value: $(params.OW_APP_JAVA_VERSION)
        - name: OW_BUILD_CONFIG_PATH
          value: $(params.OW_BUILD_CONFIG_PATH)
    #####################################################################
    - name: finalize-runtime-with-function
      taskRef:
        name: finalize-runtime-with-function
      resources:
        inputs:
          - name: app-git
            resource: app-git
            from:
              - create-jar-with-maven
          - name: runtime-git
            resource: runtime-git
            from:
              - build-runtime-with-gradle
        outputs:
          - name: app-image
            resource: app-image
      params:
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: OW_RUNTIME_CONTEXT
          value: $(params.OW_RUNTIME_CONTEXT)
        - name: MAVEN_BUILD_OUTPUT_PATH
          value: $(params.MAVEN_BUILD_OUTPUT_PATH)
        - name: JAR_NAME
          value: $(params.JAR_NAME)
        - name: OW_AUTO_INIT_MAIN
          value: $(params.OW_AUTO_INIT_MAIN)
